import { Plus_Jakarta_Sans } from "next/font/google";
import "../../public/globals.css";
import Navbar from "@/components/layouts/Navbar";
import Container from "@/components/ui/Container/Container";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
        <Navbar/>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
